### ISSUE TITLE
module.require is not available in the browser

### ISSUE THREAD

**Issue by AdrianRossouw** [rjrodger/use-plugin#4]
This means that all modules that depend on use-plugin are probably not portable to the browser environment until the implementation is rewritten to make use of the global require.

This is the relevant issue for [browserify](https://github.com/substack/node-browserify/issues/475), and the issue for [webpack](https://github.com/webpack/webpack/issues/20).

There's an added wrinkle here in that [browserify won't handle dynamic require statements](https://github.com/substack/node-browserify/issues/664), although webpack does try to do more in this regard.

**Comment by AdrianRossouw** [comment]
btw: I kind of suspect it might not be really possible to port this module to the browser completely, because it seems to depend on doing a lot of things at run-time, which need to be happening at build time via static analysis.

**Comment by rjrodger** [comment]
closing as obsoleted by https://github.com/voxgig/seneca-browser
